const state={model:'',data:null};
const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function toast(text){const el=$('#toast');el.textContent=text;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2600)}
function addMessage(role,text,meta='刚刚'){const wrap=$('#messages');const node=document.createElement('div');node.className=`message ${role}`;node.innerHTML=`<div class="message-avatar">${role==='user'?'A':'C'}</div><div><div class="message-meta">${role==='user'?'你':'CachePilot'} <span>${meta}</span></div><div class="bubble">${esc(text).replace(/\n/g,'<br>')}</div></div>`;wrap.appendChild(node);wrap.scrollTop=wrap.scrollHeight;return node}
function renderBars(traces){const el=$('#request-bars');if(!traces.length){el.innerHTML='<div class="empty-chart">暂无请求数据<br><small>发送消息后这里会自动更新</small></div>';return}const recent=traces.slice(-10);const max=Math.max(1,...recent.map(t=>t.completion_tokens||1));el.innerHTML=recent.map(t=>`<div class="bar-group" title="${esc(t.request_id)}"><i class="bar ${t.terminal_state==='REJECTED'?'reject':''}" style="height:${Math.max(8,((t.completion_tokens||1)/max)*145)}px"></i></div>`).join('');const mini=$('#mini-bars');if(mini)mini.innerHTML=recent.slice(-8).map(t=>`<i style="height:${Math.max(10,((t.completion_tokens||1)/max)*100)}%" class="${t.terminal_state==='REJECTED'?'reject':''}"></i>`).join('')}
function render(data){state.data=data;state.model=data.model;$('#model-short').textContent=data.model.split('/').pop();$('#active-sequences').innerHTML=`${data.active_sequences} <small>/ ${data.active_capacity}</small>`;$('#active-progress').style.width=`${Math.min(100,data.active_sequences/data.active_capacity*100)}%`;const kv=Math.round(data.reserved_kv_blocks/data.kv_capacity_blocks*100),peakKv=Math.round((data.peak_reserved_kv_blocks||data.reserved_kv_blocks)/data.kv_capacity_blocks*100);$('#kv-usage').textContent=`${kv}%`,$('#kv-progress').style.width=`${Math.min(100,peakKv)}%`,$('#kv-detail').textContent=`当前 ${data.reserved_kv_blocks} / ${data.kv_capacity_blocks} · 峰值 ${peakKv}%`,$('#avg-latency').innerHTML=data.avg_latency_ms?`${data.avg_latency_ms} <small>ms</small>`:'— <small>ms</small>';
$('#total-requests').textContent=data.requests;$('#success-rate').textContent=data.completed?`${Math.round(data.success/data.completed*100)}%`:'—';$('#avg-ttft').innerHTML=data.avg_ttft_ms?`${data.avg_ttft_ms}<small> ms</small>`:'—<small> ms</small>';$('#total-tokens').textContent=data.traces.reduce((n,t)=>n+(t.completion_tokens||0),0);renderBars(data.traces);const done=data.traces.filter(t=>t.terminal_state),fast=done.filter(t=>(t.total_ms||0)<500).length,medium=done.filter(t=>(t.total_ms||0)>=500&&t.total_ms<1000).length,slow=done.filter(t=>(t.total_ms||0)>=1000).length;$('#fast-count').textContent=fast;$('#medium-count').textContent=medium;$('#slow-count').textContent=slow;$('#latency-value').textContent=data.avg_latency_ms||'—';const total=done.length||1;$('#latency-donut').style.background=`conic-gradient(var(--cyan) 0 ${fast/total*100}%,var(--purple) ${fast/total*100}% ${(fast+medium)/total*100}%,#3b4455 ${(fast+medium)/total*100}% 100%)`;const miniDonut=$('#mini-donut');if(miniDonut)miniDonut.style.background=`conic-gradient(#5bc1ba 0 ${fast/total*100}%,#ebeef2 ${fast/total*100}% 100%)`;if($('#mini-fast'))$('#mini-fast').textContent=`${Math.round(fast/total*100)}%`;if($('#mini-latency'))$('#mini-latency').textContent=data.avg_latency_ms||'—';
$('#trace-count').textContent=`${data.traces.length} requests`;$('#trace-table').innerHTML=data.traces.length?data.traces.slice().reverse().map(t=>`<tr><td>${esc(t.request_id.slice(0,18))}</td><td>${esc(t.tenant_id)}</td><td><span class="status ${t.terminal_state==='SUCCEEDED'?'ok':'bad'}">${t.terminal_state||'RUNNING'}</span></td><td>${t.ttft_ms!=null?Math.round(t.ttft_ms)+' ms':'—'}</td><td>${t.total_ms!=null?Math.round(t.total_ms)+' ms':'—'}</td><td>${t.completion_tokens||0}</td></tr>`).join(''):'<tr><td colspan="6" class="empty-row">暂无 trace 记录</td></tr>'}
async function refresh(){try{const response=await fetch('/ui/dashboard');if(!response.ok)throw Error();render(await response.json())}catch(e){toast('暂时无法读取服务状态')}}
async function send(event){event.preventDefault();const input=$('#prompt'),text=input.value.trim();if(!text)return;if(!state.model){toast('模型尚未就绪');return}addMessage('user',text);input.value='';input.style.height='auto';const button=$('.send-btn');button.disabled=true;const pending=addMessage('assistant','正在思考…');try{const response=await fetch('/v1/chat/completions',{method:'POST',headers:{'Content-Type':'application/json','X-Tenant-ID':'team-a','X-Priority':'interactive'},body:JSON.stringify({model:state.model,messages:[{role:'user',content:text}],stream:false,max_tokens:256})});const payload=await response.json();if(!response.ok)throw Error(payload.error?.message||'请求失败');pending.remove();addMessage('assistant',payload.choices?.[0]?.message?.content||'请求已完成');await refresh()}catch(error){pending.remove();addMessage('assistant',`请求失败：${error.message}`);toast(error.message)}finally{button.disabled=false}}
document.querySelectorAll('.nav-item').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.nav-item').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.page').forEach(x=>x.classList.remove('active-page'));btn.classList.add('active');$(`#${btn.dataset.target}`).classList.add('active-page');$('#page-title').textContent=btn.dataset.target==='analytics'?'数据分析':'工作台'}));$('#composer').addEventListener('submit',send);$('#prompt').addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();$('#composer').requestSubmit()}});$('#prompt').addEventListener('input',e=>{e.target.style.height='auto';e.target.style.height=`${Math.min(e.target.scrollHeight,90)}px`});$('#refresh').addEventListener('click',refresh);setInterval(()=>{$('#clock').textContent=new Date().toLocaleTimeString('zh-CN',{hour12:false})},1000);setInterval(refresh,5000);refresh();
