"""CachePilot 执行器公共接口。"""

from cachepilot.executor_capabilities import (
    EXECUTOR_CAPABILITY_MATRIX,
    SIM_EXECUTOR_CAPABILITIES,
    TORCH_EXECUTOR_CAPABILITIES,
    VLLM_EXECUTOR_CAPABILITIES,
    CapabilityError,
    ExecutorCapabilities,
    IncomparableMetricError,
    capabilities_for_executor,
    metric_semantic_signature,
    require_comparable_metric,
    validate_physical_prefix_observation,
)

from .sim_executor import (
    LogicalClock,
    SimEvent,
    SimEventKind,
    SimExecutor,
    SimExecutorConfig,
    SimExecutorError,
    SimExecutorSnapshot,
    SimExecutorStats,
    SimRequest,
    SimRequestSnapshot,
    SimRequestState,
    SimulationLimitError,
    WorkerUnavailableError,
)
from .torch_executor import (
    TorchExecutor,
    TorchExecutorConfig,
    TorchExecutorError,
    TorchExecutorUnavailableError,
)
from .vllm_executor import (
    VllmExecutor,
    VllmExecutorConfig,
    VllmExecutorError,
    VllmExecutorUnavailableError,
    VllmUsage,
)

__all__ = [
    "CapabilityError",
    "EXECUTOR_CAPABILITY_MATRIX",
    "ExecutorCapabilities",
    "IncomparableMetricError",
    "LogicalClock",
    "SimEvent",
    "SimEventKind",
    "SimExecutor",
    "SimExecutorConfig",
    "SimExecutorError",
    "SimExecutorSnapshot",
    "SimExecutorStats",
    "SimRequest",
    "SimRequestSnapshot",
    "SimRequestState",
    "SimulationLimitError",
    "SIM_EXECUTOR_CAPABILITIES",
    "WorkerUnavailableError",
    "TorchExecutor",
    "TorchExecutorConfig",
    "TorchExecutorError",
    "TorchExecutorUnavailableError",
    "TORCH_EXECUTOR_CAPABILITIES",
    "VllmExecutor",
    "VllmExecutorConfig",
    "VllmExecutorError",
    "VllmExecutorUnavailableError",
    "VllmUsage",
    "VLLM_EXECUTOR_CAPABILITIES",
    "capabilities_for_executor",
    "metric_semantic_signature",
    "require_comparable_metric",
    "validate_physical_prefix_observation",
]
